# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "taxonID", # <dct_add_row>
  "scientificName", # <dct_add_row>
  "dct_terms", # <check_col_names_p>
  ":=", # <check_mapping_to_self>
  "taxonomicStatus", # <check_syn_map_to_acc>
  "acceptedNameUsageID", # <check_acc_id_has_tax_status>
  "acceptedNameUsageID", # <check_acc_id_valid_tax_status>
  "taxonomicStatus", # <check_variant_map_to_nonvar>
  "taxonomicStatus", # <check_variant_map_to_something>
  "taxonomicStatus", # <check_accepted_map_to_nothing>
  "scientificName", # <check_status_diff_p>
  "taxonomicStatus", # <check_status_diff_p>
  "dct_terms", # <dct_fill_col>
  "dct_terms", # <dct_fix_format>
  "input_type", # <dct_fix_format>
  "type", # <dct_fix_format>
  "taxonID", # <dct_modify_row_single>
  "scientificName", # <dct_modify_row_single>
  "acceptedNameUsageID", # <dct_modify_row_single>
  "taxonomicStatus", # <dct_modify_row_single>
  "check", # <dct_validate>
  "error", # <dct_validate>
  "dct_terms", # <sort_cols_dwc>
  NULL
))
