# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "taxonID", # <dct_change_status_single>
  "scientificName", # <dct_change_status_single>
  "acceptedNameUsageID", # <dct_change_status_single>
  "dct_terms", # <dct_fix_format>
  "input_type", # <dct_fix_format>
  "type", # <dct_fix_format>
  "taxonID", # <dct_validate>
  "taxonomicStatus", # <dct_validate>
  "acceptedNameUsageID", # <dct_validate>
  "dct_terms", # <dct_validate>
  NULL
))
