# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "taxonomicStatus", # <pcg_assert_tax_dat>
  "taxonID", # <pcg_assert_tax_dat>
  "taxonRemarks", # <pcg_change_status>
  NULL
))
